import { describe, expect, it } from 'vitest';
import { DEFAULT_USER_SETTINGS } from '../types/settings';
import { detectRiskPatterns } from '../lib/riskPatterns';
import { Trade } from '../types/trade';
const makeTrade=(id:string,openedAt:string,netPnL:number,lotSize=1,killzone:Trade['killzone']=null):Trade=>({id,ticket:id,sourceId:id,openedAt,closedAt:openedAt,timezone:'UTC',symbol:'EURUSD',direction:'BUY',entryPrice:1,exitPrice:1,stopLoss:null,takeProfit:null,quantity:null,lotSize,contractSize:null,grossPnL:netPnL,commission:0,swap:0,netPnL,initialRiskAmount:null,riskPercent:null,rMultiple:null,balanceBefore:null,balanceAfter:null,session:null,timeframe:'M15',setup:null,setupId:null,killzone,notes:null,emotion:null,mistake:null,tags:[],screenshotBefore:null,screenshotAfter:null,status:'CLOSED',dataQuality:'VERIFIED',createdAt:openedAt,updatedAt:openedAt});
const settings=(patch:Partial<typeof DEFAULT_USER_SETTINGS.riskPatternSettings>={})=>({...DEFAULT_USER_SETTINGS,riskPatternSettings:{...DEFAULT_USER_SETTINGS.riskPatternSettings,...patch}});
describe('proactive risk patterns',()=>{
 it('detects revenge trading after a loss',()=>{const a=detectRiskPatterns([makeTrade('loss','2026-09-01T10:00:00.000Z',-100),makeTrade('next','2026-09-01T10:10:00.000Z',20)],DEFAULT_USER_SETTINGS);expect(a.some(x=>x.type==='REVENGE_TRADING')).toBe(true)});
 it('detects four consecutive losses',()=>{const t=[1,2,3,4].map((n,i)=>makeTrade(`loss-${n}`,`2026-09-0${i+1}T10:00:00.000Z`,-10));const a=detectRiskPatterns(t,DEFAULT_USER_SETTINGS);expect(a.find(x=>x.type==='LOSS_STREAK')?.relatedTradeIds).toHaveLength(4)});
 it('detects overtrading days above 2x average',()=>{const t=[makeTrade('a','2026-09-01T10:00:00Z',10),makeTrade('b','2026-09-02T10:00:00Z',10),makeTrade('c','2026-09-03T10:00:00Z',10),makeTrade('d','2026-09-03T11:00:00Z',10),makeTrade('e','2026-09-03T12:00:00Z',10),makeTrade('f','2026-09-03T13:00:00Z',10),makeTrade('g','2026-09-03T14:00:00Z',10)];expect(detectRiskPatterns(t,DEFAULT_USER_SETTINGS).some(x=>x.type==='OVERTRADING')).toBe(true)});
 it('detects abnormal position size',()=>{const t=Array.from({length:5},(_,i)=>makeTrade(`p${i}`,`2026-09-0${i+1}T10:00:00Z`,10,1));t.push(makeTrade('big','2026-09-06T10:00:00Z',10,3));expect(detectRiskPatterns(t,DEFAULT_USER_SETTINGS).some(x=>x.type==='ABNORMAL_POSITION_SIZE')).toBe(true)});
 it('detects trading outside historically strong killzones',()=>{const t=[...Array.from({length:10},(_,i)=>makeTrade(`best${i}`,`2026-08-${String(i+1).padStart(2,'0')}T10:00:00Z`,10,1,'LONDON_OPEN')),...Array.from({length:10},(_,i)=>makeTrade(`off${i}`,`2026-08-${String(i+11).padStart(2,'0')}T22:00:00Z`,-10,1,'OFF_HOURS')];expect(detectRiskPatterns(t,settings({outsideKillzoneMinTrades:10,outsideKillzonePerformanceGap:10})).some(x=>x.type==='OUTSIDE_KILLZONE')).toBe(true)});
 it('detects recent winrate degradation',()=>{const t=[...Array.from({length:20},(_,i)=>makeTrade(`old${i}`,`2026-07-${String(i+1).padStart(2,'0')}T10:00:00Z`,10)),...Array.from({length:20},(_,i)=>makeTrade(`new${i}`,`2026-08-${String(i+1).padStart(2,'0')}T10:00:00Z`,i<5?10:-10))];expect(detectRiskPatterns(t,settings({recentWinrateWindow:20,recentWinrateDropPoints:15})).some(x=>x.type==='RECENT_WINRATE_DEGRADATION')).toBe(true)});
 it('respects configurable thresholds',()=>{const a=detectRiskPatterns([makeTrade('loss','2026-09-01T10:00:00.000Z',-100),makeTrade('next','2026-09-01T10:10:00.000Z',20)],settings({revengeWindowMinutes:5}));expect(a.some(x=>x.type==='REVENGE_TRADING')).toBe(false)});
});
