import { Trade } from '../types/trade';
import { UserSettings } from '../types/settings';
export type RiskPatternType='REVENGE_TRADING'|'LOSS_STREAK'|'OVERTRADING'|'ABNORMAL_POSITION_SIZE'|'OUTSIDE_KILLZONE'|'RECENT_WINRATE_DEGRADATION';
export interface RiskAlert{id:string;type:RiskPatternType;title:string;explanation:string;detectedAt:string;relatedTradeIds:string[];relatedTradeLabels:string[];read:boolean;dismissed:boolean;}
export interface RiskPatternConfig{revengeWindowMinutes:number;revengeMinLotMultiplier:number;lossStreakThreshold:number;overtradingDailyMultiplier:number;abnormalLotMultiplier:number;recentWinrateWindow:number;recentWinrateDropPoints:number;outsideKillzoneMinTrades:number;outsideKillzonePerformanceGap:number;}
export const DEFAULT_RISK_PATTERN_CONFIG:RiskPatternConfig={revengeWindowMinutes:15,revengeMinLotMultiplier:1.5,lossStreakThreshold:4,overtradingDailyMultiplier:2,abnormalLotMultiplier:3,recentWinrateWindow:20,recentWinrateDropPoints:15,outsideKillzoneMinTrades:10,outsideKillzonePerformanceGap:10};
const finite=(v:number|null|undefined)=>typeof v==='number'&&Number.isFinite(v)?v:null;
export function getRiskPatternConfig(settings:UserSettings):RiskPatternConfig{const r=settings.riskPatternSettings;return{revengeWindowMinutes:Math.min(60,Math.max(1,Math.round(r?.revengeWindowMinutes??15))),revengeMinLotMultiplier:Math.min(10,Math.max(1,r?.revengeMinLotMultiplier??1.5)),lossStreakThreshold:Math.min(20,Math.max(2,Math.round(r?.lossStreakThreshold??4))),overtradingDailyMultiplier:Math.min(10,Math.max(1.1,r?.overtradingDailyMultiplier??2)),abnormalLotMultiplier:Math.min(10,Math.max(1.5,r?.abnormalLotMultiplier??3)),recentWinrateWindow:Math.min(50,Math.max(10,Math.round(r?.recentWinrateWindow??20))),recentWinrateDropPoints:Math.min(50,Math.max(5,r?.recentWinrateDropPoints??15)),outsideKillzoneMinTrades:Math.min(100,Math.max(5,Math.round(r?.outsideKillzoneMinTrades??10))),outsideKillzonePerformanceGap:Math.min(50,Math.max(5,r?.outsideKillzonePerformanceGap??10))};}
const sortTrades=(t:Trade[])=>[...t].filter(x=>Boolean(x.openedAt)).sort((a,b)=>new Date(a.openedAt).getTime()-new Date(b.openedAt).getTime());
const tradeLabel=(t:Trade)=>`${t.symbol}${t.ticket?` #${t.ticket}`:''}`; const alertId=(type:RiskPatternType,ids:string[])=>`${type}:${ids.join(',')}`;
export function detectRiskPatterns(trades:Trade[],settings:UserSettings):RiskAlert[]{const ordered=sortTrades(trades),c=getRiskPatternConfig(settings),alerts:RiskAlert[]=[],now=new Date().toISOString();
  for(let i=1;i<ordered.length;i++){const p=ordered[i-1],cur=ordered[i],pnl=finite(p.netPnL);if(pnl===null||pnl>=0)continue;const gap=(new Date(cur.openedAt).getTime()-new Date(p.openedAt).getTime())/60000;if(gap<0||gap>c.revengeWindowMinutes)continue;const lots=ordered.slice(Math.max(0,i-20),i).map(t=>finite(t.lotSize)).filter((v):v is number=>v!==null&&v>0),avg=lots.length?lots.reduce((s,v)=>s+v,0)/lots.length:null,lot=finite(cur.lotSize),up=avg!==null&&lot!==null&&lot>=avg*c.revengeMinLotMultiplier,ids=[p.id,cur.id];alerts.push({id:alertId('REVENGE_TRADING',ids),type:'REVENGE_TRADING',title:'Revenge trading potentiel',explanation:up?`Un trade a été ouvert ${Math.round(gap)} min après une perte, avec une taille d’environ ${((lot!/avg!)*100).toFixed(0)} % de la moyenne récente.`:`Un trade a été ouvert ${Math.round(gap)} min après une perte, sous le seuil configuré de ${c.revengeWindowMinutes} min.`,detectedAt:now,relatedTradeIds:ids,relatedTradeLabels:ids.map(id=>tradeLabel(ordered.find(t=>t.id===id)!)),read:false,dismissed:false});}
  let streak:Trade[]=[];const flush=()=>{if(streak.length>=c.lossStreakThreshold){const ids=streak.map(t=>t.id);alerts.push({id:alertId('LOSS_STREAK',ids),type:'LOSS_STREAK',title:`${streak.length} pertes consécutives`,explanation:`Une série de ${streak.length} pertes consécutives a été détectée. Le seuil configuré est de ${c.lossStreakThreshold}.`,detectedAt:now,relatedTradeIds:ids,relatedTradeLabels:streak.map(tradeLabel),read:false,dismissed:false});}streak=[];};for(const t of ordered){const p=finite(t.netPnL);if(p!==null&&p<0)streak.push(t);else if(p!==null&&p>0)flush();}flush();
  const dayCounts=new Map<string,number>();for(const t of ordered){const d=t.openedAt.slice(0,10);dayCounts.set(d,(dayCounts.get(d)||0)+1);}if(dayCounts.size>=3){const avg=[...dayCounts.values()].reduce((s,v)=>s+v,0)/dayCounts.size;for(const[d,n]of dayCounts)if(n>avg*c.overtradingDailyMultiplier){const ids=ordered.filter(t=>t.openedAt.slice(0,10)===d).map(t=>t.id);alerts.push({id:alertId('OVERTRADING',ids),type:'OVERTRADING',title:'Sur-trading potentiel',explanation:`La journée du ${d} compte ${n} trades, contre une moyenne historique de ${avg.toFixed(1)} par jour.`,detectedAt:now,relatedTradeIds:ids,relatedTradeLabels:ids.slice(0,8).map(id=>tradeLabel(ordered.find(t=>t.id===id)!)),read:false,dismissed:false});}}
  for(let i=0;i<ordered.length;i++){const lot=finite(ordered[i].lotSize),prev=ordered.slice(Math.max(0,i-20),i).map(t=>finite(t.lotSize)).filter((v):v is number=>v!==null&&v>0);if(lot===null||prev.length<5)continue;const avg=prev.reduce((s,v)=>s+v,0)/prev.length;if(lot<avg*c.abnormalLotMultiplier)continue;const after=i>0&&(finite(ordered[i-1].netPnL)??0)<0,ids=after?[ordered[i-1].id,ordered[i].id]:[ordered[i].id];alerts.push({id:alertId('ABNORMAL_POSITION_SIZE',ids),type:'ABNORMAL_POSITION_SIZE',title:'Taille de position anormale',explanation:`La taille de ${lot} lot est ${(lot/avg*100).toFixed(0)} % de la moyenne des ${prev.length} trades précédents${after?', après une perte':''}.`,detectedAt:now,relatedTradeIds:ids,relatedTradeLabels:ids.map(id=>tradeLabel(ordered.find(t=>t.id===id)!)),read:false,dismissed:false});}
  // Historical killzone edge: identify the best recorded killzones, then flag a material share of trades outside them.
  const byKz=new Map<string,Trade[]>();for(const t of ordered){if(!t.killzone||t.killzone==='OFF_HOURS'||finite(t.netPnL)===null)continue;const k=String(t.killzone).toUpperCase();byKz.set(k,[...(byKz.get(k)||[]),t]);}
  const qualified=[...byKz.entries()].filter(([,ts])=>ts.length>=5).sort((a,b)=>{const aw=a[1].filter(t=>(t.netPnL??0)>0).length/a[1].length;const bw=b[1].filter(t=>(t.netPnL??0)>0).length/b[1].length;return bw-aw;});
  if(qualified.length){const best=qualified.filter(([,ts])=>{const wr=ts.filter(t=>(t.netPnL??0)>0).length/ts.length*100;const top=qualified[0][1].filter(t=>(t.netPnL??0)>0).length/qualified[0][1].length*100;return top-wr<c.outsideKillzonePerformanceGap;}).map(([k])=>k);const outside=ordered.filter(t=>{const k=t.killzone?String(t.killzone).toUpperCase():'OFF_HOURS';return !best.includes(k);}).filter(t=>finite(t.netPnL)!==null);const inside=ordered.filter(t=>{const k=t.killzone?String(t.killzone).toUpperCase():'OFF_HOURS';return best.includes(k);}).filter(t=>finite(t.netPnL)!==null);if(outside.length>=c.outsideKillzoneMinTrades&&inside.length>=c.outsideKillzoneMinTrades){const owr=outside.filter(t=>(t.netPnL??0)>0).length/outside.length*100,iwr=inside.filter(t=>(t.netPnL??0)>0).length/inside.length*100;if(iwr-owr>=c.outsideKillzonePerformanceGap){const ids=outside.slice(-Math.min(10,outside.length)).map(t=>t.id);alerts.push({id:alertId('OUTSIDE_KILLZONE',ids),type:'OUTSIDE_KILLZONE',title:'Trading hors killzones habituelles',explanation:`Le winrate des trades dans vos killzones historiquement les plus performantes est ${iwr.toFixed(0)} %, contre ${owr.toFixed(0)} % hors de ces zones.`,detectedAt:now,relatedTradeIds:ids,relatedTradeLabels:ids.map(id=>tradeLabel(ordered.find(t=>t.id===id)!)),read:false,dismissed:false});}}}
  const resulted=ordered.filter(t=>finite(t.netPnL)!==null);if(resulted.length>=c.recentWinrateWindow+10){const recent=resulted.slice(-c.recentWinrateWindow),hist=resulted.slice(0,-c.recentWinrateWindow),rw=recent.filter(t=>(t.netPnL??0)>0).length/recent.length*100,hw=hist.filter(t=>(t.netPnL??0)>0).length/hist.length*100;if(hw-rw>=c.recentWinrateDropPoints){const ids=recent.map(t=>t.id);alerts.push({id:alertId('RECENT_WINRATE_DEGRADATION',ids),type:'RECENT_WINRATE_DEGRADATION',title:'Dégradation du winrate récent',explanation:`Le winrate des ${recent.length} derniers trades est de ${rw.toFixed(0)} %, contre ${hw.toFixed(0)} % sur l’historique précédent.`,detectedAt:now,relatedTradeIds:ids,relatedTradeLabels:recent.slice(-8).map(tradeLabel),read:false,dismissed:false});}}
  return alerts;
}
