import React, { useEffect, useRef, useState } from 'react';
import { AlertTriangle, Bot, Search, Send, Sparkles, Trash2, User } from 'lucide-react';
import { motion } from 'motion/react';
import { useAICoach } from '../hooks/useAICoach';
import { Trade } from '../types/trade';

interface CoachViewProps { trades?: unknown[]; setups?: unknown[]; currency?: string; initialBalance?: number; }
const suggestions = ['Compare mes deux dernières semaines', 'Montre-moi mes 5 pires trades', 'Quelle est ma performance sur GBPUSD ce mois-ci ?', 'Donne-moi mes statistiques sur la dernière semaine'];
function renderText(text: string) { return text.split('\n').map((line, index) => <React.Fragment key={`${index}-${line}`}>{line.split(/(\*\*.*?\*\*)/g).map((part, i) => part.startsWith('**') && part.endsWith('**') ? <strong key={i}>{part.slice(2, -2)}</strong> : <React.Fragment key={i}>{part}</React.Fragment>)}{index < text.split('\n').length - 1 && <br />}</React.Fragment>); }
export const CoachView: React.FC<CoachViewProps> = ({ trades = [], currency = 'USD', initialBalance = 10000 }) => {
  const tradeData = trades as Trade[]; const results = tradeData.map(t => t.netPnL).filter((v): v is number => typeof v === 'number'); const wins = results.filter(v => v > 0).length; const losses = results.filter(v => v < 0).length; const pnl = results.reduce((sum, v) => sum + v, 0);
  const context = { summary: { totalTrades: tradeData.length, tradesWithResult: results.length, wins, losses, winrate: results.length ? wins / results.length * 100 : 0, pnl, currency, initialBalance } };
  const { messages, isLoading, isUsingTool, toolName, isReady, sendMessage, clearHistory, dailyCount, dailyLimit } = useAICoach(context); const [input, setInput] = useState(''); const bottomRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' }); }, [messages, isLoading, isUsingTool]);
  const submit = async () => { const value = input.trim(); if (!value || isLoading || !isReady) return; setInput(''); await sendMessage(value); inputRef.current?.focus(); }; const onKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void submit(); } };
  const toolLabel = toolName === 'getTradesByPeriod' ? 'Analyse de vos trades sur la période…' : toolName === 'getStatsForFilter' ? 'Calcul de vos statistiques filtrées…' : toolName === 'getBestTrades' ? 'Recherche de vos meilleurs trades…' : toolName === 'getWorstTrades' ? 'Recherche de vos pires trades…' : 'Analyse de vos données…';
  return <div id="view-coach" className="space-y-6 font-sans">
    <div className="p-6 rounded-3xl border border-[#ECE7FC] dark:border-[#292E38] bg-white dark:bg-[#12151D] shadow-sm"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="p-2.5 rounded-2xl bg-[#F5EEFF] dark:bg-[#FF8A00]/10 text-[#6D19E8] dark:text-[#FF8A00]"><Bot className="w-5 h-5" /></div><div><div className="flex items-center gap-2 flex-wrap"><h2 className="text-base font-bold">Trading Coach</h2><span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-200">Gemini Connecté</span></div><p className="text-xs text-[#6B668D] mt-1">Le coach peut consulter précisément vos données locales pendant la conversation.</p></div></div><button type="button" onClick={() => void clearHistory()} disabled={isLoading || !isReady} className="flex items-center gap-1.5 px-3.5 py-2 text-xs font-bold text-[#6B668D] bg-[#FAF8FF] border border-[#ECE7FC] rounded-2xl disabled:opacity-50"><Trash2 className="w-3.5 h-3.5" /> Effacer la conversation</button></div></div>
    <div className="rounded-3xl border border-[#ECE7FC] dark:border-[#292E38] bg-white dark:bg-[#12151D] shadow-sm overflow-hidden flex flex-col h-[min(700px,calc(100vh-250px))] min-h-[560px]">
      <div className="px-5 py-3.5 border-b border-[#ECE7FC] dark:border-[#292E38] bg-[#FAF8FF] dark:bg-[#181C25] flex items-center justify-between"><div className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" /><span className="text-xs font-bold">Conversation active</span></div><span className="text-[11px] text-[#8E89AF] font-medium">{dailyCount}/{dailyLimit} messages aujourd’hui</span></div>
      <div className="flex-1 overflow-y-auto px-4 sm:px-6 py-6 space-y-5">
        {messages.map(message => { const isUser = message.role === 'user'; return <motion.div key={message.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className={`flex items-end gap-2.5 ${isUser ? 'justify-end' : 'justify-start'}`}>{!isUser && <div className={`w-8 h-8 rounded-xl shrink-0 flex items-center justify-center ${message.isError ? 'bg-red-50 text-red-600' : 'bg-[#F5EEFF] text-[#6D19E8]'}`}>{message.isError ? <AlertTriangle className="w-4 h-4" /> : <Bot className="w-4 h-4" />}</div>}<div className={`max-w-[85%] sm:max-w-[72%] rounded-2xl px-4 py-3 text-sm leading-relaxed break-words ${isUser ? 'rounded-br-md bg-[#6D19E8] text-white' : message.isError ? 'rounded-bl-md bg-red-50 text-red-700 border border-red-200' : 'rounded-bl-md bg-[#F7F5FC] dark:bg-[#1A1E28] text-[#29263D] border border-[#ECE7FC]'}`}>{renderText(message.text)}</div>{isUser && <div className="w-8 h-8 rounded-xl shrink-0 flex items-center justify-center bg-[#FFF1E3] text-[#D96D00]"><User className="w-4 h-4" /></div>}</motion.div>; })}
        {isUsingTool && <div className="flex items-center gap-2 pl-10 text-[11px] text-[#7A7299] font-medium"><Search className="w-3.5 h-3.5 text-[#6D19E8] animate-pulse" /><span>{toolLabel}</span></div>}
        {isLoading && !isUsingTool && <div className="flex items-center gap-2 pl-10 text-xs text-[#6B668D]"><Bot className="w-4 h-4" /> Coach est en train d’écrire <span className="flex gap-1"><span className="w-1.5 h-1.5 rounded-full bg-[#6D19E8] animate-bounce" /><span className="w-1.5 h-1.5 rounded-full bg-[#6D19E8] animate-bounce [animation-delay:100ms]" /><span className="w-1.5 h-1.5 rounded-full bg-[#6D19E8] animate-bounce [animation-delay:200ms]" /></span></div>}
        <div ref={bottomRef} />
      </div>
      <div className="shrink-0 border-t border-[#ECE7FC] dark:border-[#292E38] bg-white dark:bg-[#12151D]">{messages.length === 1 && !isLoading && <div className="px-4 sm:px-6 pt-4"><div className="flex items-center gap-2 mb-2 text-[10px] font-bold uppercase tracking-wider text-[#8E89AF]"><Sparkles className="w-3.5 h-3.5 text-[#6D19E8]" /> Suggestions</div><div className="flex flex-wrap gap-2">{suggestions.map(s => <button key={s} type="button" onClick={() => { setInput(s); inputRef.current?.focus(); }} className="px-3 py-2 rounded-xl border border-[#E5DDF8] bg-[#FAF8FF] text-[11px] font-semibold">{s}</button>)}</div></div>}
      <form onSubmit={e => { e.preventDefault(); void submit(); }} className="p-4 sm:p-5"><div className="flex items-end gap-2 p-2 rounded-2xl border border-[#DDD5FA] bg-[#FAF8FF] dark:bg-[#181C25]"><textarea ref={inputRef} value={input} onChange={e => setInput(e.target.value)} onKeyDown={onKeyDown} disabled={isLoading || !isReady} rows={1} placeholder="Écrivez votre message au coach…" className="flex-1 resize-none min-h-10 px-2 py-2.5 bg-transparent outline-none text-sm" /><button type="submit" disabled={!input.trim() || isLoading || !isReady} className="w-10 h-10 shrink-0 rounded-xl flex items-center justify-center bg-[#6D19E8] dark:bg-[#FF8A00] text-white disabled:opacity-40"><Send className="w-4 h-4" /></button></div><p className="mt-2 text-[10px] text-center text-[#9A95B2]">Entrée pour envoyer • Maj + Entrée pour aller à la ligne</p></form></div>
    </div>
  </div>;
};