function safeNum(value: any): number | null { const n = Number(value); return Number.isFinite(n) ? n : null; }
function deterministicReply(userMessage: string, metrics: any, history: any[] = []): string {
  const question = String(userMessage || '').trim(); const q = question.toLowerCase(); const total = Number(metrics?.totalTrades || 0);
  const wr=safeNum(metrics?.winrate), exp=safeNum(metrics?.expectancy), pnl=safeNum(metrics?.totalPnL), pf=safeNum(metrics?.profitFactor), dd=safeNum(metrics?.maxDrawdownPercent), score=safeNum(metrics?.score);
  const base=`Sur ${total} trades, ton Win Rate est ${wr==null?'N/A':wr.toFixed(1)+'%'}, ton expectancy ${exp==null?'N/A':'$'+exp.toFixed(2)} et ton PnL ${pnl==null?'N/A':'$'+pnl.toFixed(2)}.`;
  if(q.includes('leak')||q.includes('erreur')||q.includes('faiblesse')) return `🎯 **Mon avis sur ton principal leak**\n\n${base}\n\nJe chercherais le groupe qui détruit le plus ton expectancy : setup, session, actif ou comportement. Compare les pertes par groupe puis vérifie si le problème vient de la sélection ou de l'exécution. Un leak avec peu de trades ne doit pas être traité comme une conclusion définitive.`;
  if(q.includes('setup')||q.includes('meilleur')||q.includes('edge')) { const edges=Array.isArray(metrics?.edges)&&metrics.edges.length?metrics.edges.slice(0,5).join(' ; '):'aucun groupe suffisamment documenté'; return `📈 **Ce que j'en pense**\n\n${base}\n\nGroupes actuellement remontés : ${edges}.\n\nJe privilégierais expectancy positive + échantillon suffisant + drawdown acceptable, plutôt que le meilleur Win Rate seul.`; }
  if(q.includes('comment')||q.includes('gérer')||q.includes('gere')||q.includes('que faire')||q.includes('conseil')||q.includes('pense')||q.includes('avis')||q.includes('devrais')||q.includes('pourquoi')||q.includes('est-ce')||q.includes('est ce')) return `🧠 **Mon avis**\n\n${base}\n\nTa question est ouverte. Avec tes données, je commencerais par **${metrics?.currentFocus||'protéger la qualité d’exécution et la stabilité du risque'}**.\n\n**Comment le gérer :**\n1. définis une règle mesurable ;\n2. applique-la sur les prochains trades ;\n3. mesure l'effet sur PnL et expectancy ;\n4. ne change pas plusieurs variables à la fois.\n\n${dd!=null?`Ton drawdown observé est de ${dd.toFixed(1)}%, donc toute amélioration doit préserver cette contrainte.`:''}`;
  if(q.includes('discipline')||q.includes('risque')||q.includes('risk')) return `🛡️ **Risque & discipline**\n\n${base}\n\nJe vérifierais stabilité de la taille de position, respect du Stop Loss et comportement après une perte. ${pf!=null?`Profit Factor : ${pf.toFixed(2)}.`:''}`;
  if(q.includes('bilan')||q.includes('résumé')||q.includes('resume')||q.includes('global')) return `📊 **Bilan**\n\n${base}\n\n${pf!=null?`Profit Factor : ${pf.toFixed(2)}.`:''} ${dd!=null?`Drawdown max : ${dd.toFixed(1)}%.`:''} ${score!=null?`Score : ${score.toFixed(0)}/100.`:''}`;
  return `💬 **Je t'écoute**\n\nTu me demandes : « ${question} »\n\n${base}\n\nJe peux analyser une question ouverte, une décision ou une situation de trading. Donne-moi le contexte et je le relierai à tes données plutôt que de renvoyer un diagnostic standard. ${history.length?`La conversation contient déjà ${history.length} messages récents.`:''}`;
}
export default async function handler(req:any,res:any){
  if(req.method!=='POST') return res.status(405).json({error:'Method not allowed'});
  const {userMessage,metricsContext,chatHistory}=req.body||{}; const question=String(userMessage||'').trim();
  if(!question) return res.status(400).json({error:'userMessage is required'});
  const apiKey=process.env.GEMINI_API_KEY||process.env.GOOGLE_AI_API_KEY;
  if(apiKey) try{
    const history=Array.isArray(chatHistory)?chatHistory.slice(-8).map((m:any)=>({role:m.sender==='user'?'user':'model',parts:[{text:String(m.text||'')}]})):[];
    const prompt=`Tu es le coach de trading personnel de l'utilisateur. Réponds en français, naturellement et de façon conversationnelle. Réponds aussi aux questions ouvertes comme « tu en penses quoi ? », « comment je peux gérer ça ? », « qu'est-ce que tu ferais ? ». Utilise uniquement les données fournies. Distingue faits, interprétation et conseil. Ne promets jamais de gains et ne fabrique aucune statistique.\n\nQUESTION : ${question}\n\nCONTEXTE : ${JSON.stringify(metricsContext)}`;
    const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${encodeURIComponent(apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[...history,{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:0.55,maxOutputTokens:900}})});
    if(response.ok){const data:any=await response.json();const reply=data?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join(' ').trim();if(reply)return res.status(200).json({reply});}
  }catch(error){console.error('Gemini coach error',error)}
  return res.status(200).json({reply:deterministicReply(question,metricsContext,Array.isArray(chatHistory)?chatHistory:[])});
}
